apiVersion: v1
kind: Service
metadata:
  name: wordpress-postgresql
  labels:
    app: wordpress
spec:
  ports:
    - port: 5432
  selector:
    app: wordpress
    tier: postgresql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-postgresql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: postgresql
    spec:
      containers:
      - image: postgres:9.4
        name: postgresql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-pass
              key: password
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pv-claim
